### ISSUE TITLE
仿真模式步骤四生成任务执行配置文件报错

### ISSUE THREAD

**Issue by ClaudiaCumberbatch** [asterinas/trustflow#96]
### Issue Type

Bug

### Source

binary

### Capsule Manager Version

0.4.0b0

### Capsule Manager SDK Version

0.4.0b0

### Tee Apps Version

0.4.0b0

### OS Platform and Distribution

Ubuntu 20.04.6 LTS

### Python version

3.8.10

### What happend and What you expected to happen.

大佬您好！
我在仿真模式下用train_test_split.json生成train_test_split_task.json的时候遇到下面的报错，请问应该怎么解决？我查看源代码发现convert.py文件需要sf_node_eval_param这个key，psi.json在这个过程中不会出问题，因为[这里](https://www.secretflow.org.cn/zh-CN/docs/trustflow/main/architecture/apps/intersect#id3)提供的代码里有"sf_node_eval_param"，而train_test_split.json文件里没有这个key。

```shell
@hpclab03:/host/integration_test# python convert.py --cert_path carol.crt --prikey_path carol.key --task_config_path train_test_split.json --scope default --capsule_manager_endpoint 127.0.0.1:8888 --tee_task_config_path train_test_split_task.json
Traceback (most recent call last):
  File "convert.py", line 117, in <module>
    convert_to_tee_task_config()
  File "/home/teeapp/python/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/teeapp/python/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/teeapp/python/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/teeapp/python/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "convert.py", line 84, in convert_to_tee_task_config
    node_eval_param_json = json.dumps(origin_json["sf_node_eval_param"])
KeyError: 'sf_node_eval_param'
```

### Reproduction code to reproduce the issue.

```shell
python convert.py --cert_path carol.crt --prikey_path carol.key --task_config_path train_test_split.json --scope default --capsule_manager_endpoint 127.0.0.1:8888 --tee_task_config_path train_test_split_task.json
```

**Comment by zimu-yuxi** [comment]
感谢，可以参考[这里](https://github.com/asterinas/trustflow-teeapps/blob/0.4.0b0/integration_test/train_test_split.json)

**Comment by ClaudiaCumberbatch** [comment]
谢谢！所以网页里给的应用代码是有缺失的？也许你们可以更正一下。
